name: Build Pico2 Firmware

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies and ARM GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential python3 gcc-arm-none-eabi libnewlib-arm-none-eabi

    - name: Build MicroPython Cross-Compiler
      run: |
        make -C mpy-cross

    - name: Build Pico 2 Firmware
      run: |
        cd ports/rp2
        make BOARD=RPI_PICO2 USER_C_MODULES=$(pwd)/mdx
        
    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pico2-firmware
        path: ports/rp2/build*/**/firmware.uf2
